name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  deployment_job:

    strategy:
      matrix:
        node-version: [ '20.x' ]

    runs-on: ubuntu-latest
    name: ssh push
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint

      - run: mkdir -p "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package"
      - run: cp -r "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/src" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package.json" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package-lock.json" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/Dockerfile" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/.dockerignore" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/compose.yaml" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/tsconfig.json" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"
      - run: cp "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/tslint.json" "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package/"

      - name: SSH push
        uses: ErenKrt/ssh-push@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "/home/runner/work/ekosystem-waste-table-json/ekosystem-waste-table-json/package"
          destination: "/home/pi/workspace/eko-waste-table/web.zip"
          scripts: unzip -o /home/pi/workspace/eko-waste-table/web.zip -d /home/pi/workspace/eko-waste-table/ && rm /home/pi/workspace/eko-waste-table/web.zip && cd /home/pi/workspace/eko-waste-table/ && docker compose up -d --build
