# ssh pi@home.dobrastronka.pl -p 22222

# ~/workspace/eko-waste-table
# zmiana na branchu -> wyślij pliki Dockerfile, compose.yaml, package.json, package-lock.json, src/
#


            - name: SSH Push
  # You may pin to the exact commit or the version.
  # uses: ErenKrt/ssh-push@cea145c9f5cc7a0a12e8151ac946e6d2fe565fd7
  uses: ErenKrt/ssh-push@1.3
  with:
    # IP Address of remote host
    host: home.dobrastronka.pl
    # Port of SSH Protocol
    port: 22222
    # Username of SSH user
    username: pi
    # Password of user
    password: 
    # Folder/File to be transferred
    source: src
    # Destination of source archive file
    destination: ~/workspace/eko-waste-table/src
    # Execute commands after transfer source file
    scripts: echo "ok"
          
